### ISSUE TITLE
Can't create a branch for PR to support Flutter >1.22 

### ISSUE THREAD

**Issue by Vov4yk** [kikuchy/plain_notification_token#3]
I want to create PR related to Flutter >=1.22 support. 
But have no access to push a feature branch.

**Comment by kikuchy** [comment]
@Vov4yk Sorry for late reply and thank you for your contribution!

Please try to make PR from your forked repository like this -> https://github.com/kikuchy/plain_notification_token/compare/master...Vov4yk:master

**Comment by kikuchy** [comment]
Maybe it solved at https://github.com/kikuchy/plain_notification_token/pull/8
