### ISSUE TITLE
not Supporting Android

### ISSUE THREAD

**Issue by zionnite** [kikuchy/plain_notification_token#9]
Hello sir,
good day sir,your package is one of the simplest that talks about getting the token for ios, but unfortunately I can use it because I keep getting warning like this

```
The plugin `plain_notification_token` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

```
please how do I resolve this?
I saw that someone made a pull request, please how do I use the pull request??
thanks sir

**Comment by kikuchy** [comment]
dup https://github.com/kikuchy/plain_notification_token/issues/7

Sorry but I'll close it.
